--enable-features=CanvasOopRasterization,UseChromeOSDirectVideoDecoder,PlatformHEVCDecoderSupport,AcceleratedVideoEncoder,AcceleratedVideoDecodeLinuxGL,AcceleratedVideoDecodeLinuxZeroCopyGL,SkiaGraphite,UseVulkanForWebGL,Vulkan,DefaultANGLEVulkan,VulkanFromANGLE,VaapiVideoDecoder,VaapiIgnoreDriverChecks
--enable-blink-features=MiddleClickAutoscroll
--gtk-version=4
--enable-unsafe-webgpu
